# Campus-Sustainability-dashboard
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

# Page Configuration
st.set_page_config(
    page_title="Campus Sustainability Dashboard",
    page_icon="🌱",
    layout="wide"
)

# ---------------------------------------------------------
# MOCK DATASETS
# Tracks energy, water, recycling, and transportation data
# ---------------------------------------------------------
facilities_data = pd.DataFrame({
    "Facility": [
        "Science & Engineering Complex",
        "North Quad Dorms",
        "Main Student Union",
        "University Library",
        "Athletics Arena"
    ],
    "Electricity_kWh": [42000, 28000, 31000, 19500, 38000],
    "Water_Gallons": [185000, 340000, 210000, 95000, 260000],
    "Waste_Generated_Tons": [18.2, 24.5, 30.1, 8.4, 22.0],
    "Landfill_Diversion_Pct": [62.5, 48.0, 74.2, 81.0, 53.0]
})

commute_data = pd.DataFrame({
    "Mode": ["Single Occupant Vehicle", "Carpool", "Campus Shuttle / Bus", "Bicycle / E-Scooter", "Walking"],
    "Share_Pct": [44.0, 14.0, 22.0, 11.0, 9.0],
    "Emissions_MTCO2e": [210.5, 52.1, 48.2, 0.0, 0.0]
})

# ---------------------------------------------------------
# HEADER & OVERVIEW
# ---------------------------------------------------------
st.title("🌱 Campus Sustainability Dashboard")
st.markdown(
    "Tracks energy, water, recycling, and transportation data to help "
    "a campus identify environmental improvements and target green retrofits."
)
st.divider()

# Top-level KPIs
total_energy = facilities_data["Electricity_kWh"].sum()
total_water = facilities_data["Water_Gallons"].sum()
avg_diversion = facilities_data["Landfill_Diversion_Pct"].mean()
total_commute_emissions = commute_data["Emissions_MTCO2e"].sum()

col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Campus Power", f"{total_energy:,.0f} kWh", delta="-4.2% vs last mo")
col2.metric("Total Water Consumed", f"{total_water:,.0f} Gal", delta="+1.8% vs last mo", delta_color="inverse")
col3.metric("Avg Waste Diversion", f"{avg_diversion:.1f}%", delta="+6.0% vs target")
col4.metric("Commuter Emissions", f"{total_commute_emissions:.1f} MT CO2e", delta="-2.5% vs baseline")

st.divider()

# ---------------------------------------------------------
# MAIN CHARTS: ENERGY, WATER, WASTE, COMMUTE
# ---------------------------------------------------------
tab_facilities, tab_transit, tab_improvements = st.tabs([
    "🏢 Facility Resource Breakdown",
    "🚌 Transportation & Commuter Footprint",
    "🎯 Environmental Improvement Modeler"
])

with tab_facilities:
    st.subheader("Building-Level Resource Monitoring")
    col_left, col_right = st.columns(2)

    with col_left:
        fig_energy = px.bar(
            facilities_data,
            x="Facility",
            y="Electricity_kWh",
            title="Electricity Consumption by Building (kWh)",
            color="Electricity_kWh",
            color_continuous_scale="Blues"
        )
        fig_energy.update_layout(xaxis_tickangle=-30)
        st.plotly_chart(fig_energy, use_container_width=True)

    with col_right:
        fig_water = px.bar(
            facilities_data,
            x="Facility",
            y="Water_Gallons",
            title="Monthly Water Use by Building (Gallons)",
            color="Water_Gallons",
            color_continuous_scale="Teal"
        )
        fig_water.update_layout(xaxis_tickangle=-30)
        st.plotly_chart(fig_water, use_container_width=True)

    st.subheader("Waste Generation vs. Landfill Diversion Rate")
    fig_waste = px.scatter(
        facilities_data,
        x="Waste_Generated_Tons",
        y="Landfill_Diversion_Pct",
        size="Waste_Generated_Tons",
        color="Facility",
        text="Facility",
        title="Waste Mass vs. Recycling/Compost Diversion Rate",
        labels={"Waste_Generated_Tons": "Total Waste (Tons)", "Landfill_Diversion_Pct": "Diversion Rate (%)"}
    )
    fig_waste.update_traces(textposition='top center')
    st.plotly_chart(fig_waste, use_container_width=True)

with tab_transit:
    st.subheader("Campus Commuter Split & Carbon Impact")
    col_t1, col_t2 = st.columns(2)

    with col_t1:
        fig_modal = px.pie(
            commute_data,
            names="Mode",
            values="Share_Pct",
            title="Commuter Modal Share (%)",
            hole=0.45
        )
        st.plotly_chart(fig_modal, use_container_width=True)

    with col_t2:
        fig_emissions = px.bar(
            commute_data,
            x="Mode",
            y="Emissions_MTCO2e",
            title="Emissions Generated by Travel Mode (MT CO2e)",
            color="Emissions_MTCO2e",
            color_continuous_scale="Reds"
        )
        fig_emissions.update_layout(xaxis_tickangle=-25)
        st.plotly_chart(fig_emissions, use_container_width=True)

# ---------------------------------------------------------
# SCENARIO PLANNER / ENVIRONMENTAL IMPROVEMENTS
# Helps a campus identify environmental improvements
# ---------------------------------------------------------
with tab_improvements:
    st.subheader("Interactive Intervention Modeling")
    st.caption("Adjust policy targets below to project campus carbon reductions.")

    ctrl_col1, ctrl_col2, ctrl_col3 = st.columns(3)
    with ctrl_col1:
        solar_capacity = st.slider("Rooftop Solar Canopy Addition (kW)", 0, 500, 150, step=25)
    with ctrl_col2:
        compost_mandate = st.slider("Target Composting & Recycling Boost (%)", 0, 40, 15, step=5)
    with ctrl_col3:
        transit_shift = st.slider("SOV Commuters Shifted to Transit / Bike (%)", 0, 50, 20, step=5)

    # Projected Savings Arithmetic
    # ~0.4 kg CO2e saved per kWh of solar generated annually (approx 1200 kWh/kW)
    projected_solar_kwh = solar_capacity * 1200 / 12  # monthly estimate
    co2_saved_energy = (projected_solar_kwh * 0.000386) # MT CO2e
    
    # Transportation savings from shifted single-occupant drivers
    sov_baseline_emissions = commute_data.loc[commute_data["Mode"] == "Single Occupant Vehicle", "Emissions_MTCO2e"].values[0]
    co2_saved_transit = sov_baseline_emissions * (transit_shift / 100.0)

    # Landfill methane reduction
    total_waste = facilities_data["Waste_Generated_Tons"].sum()
    diverted_waste_tons = total_waste * (compost_mandate / 100.0)
    co2_saved_waste = diverted_waste_tons * 0.95 # MT CO2e equivalent

    total_co2_offset = co2_saved_energy + co2_saved_transit + co2_saved_waste

    st.markdown("### Projected Monthly Reductions")
    r_col1, r_col2, r_col3, r_col4 = st.columns(4)
    r_col1.metric("Grid Energy Replaced", f"{projected_solar_kwh:,.0f} kWh/mo")
    r_col2.metric("Landfill Waste Prevented", f"{diverted_waste_tons:.1f} Tons/mo")
    r_col3.metric("Vehicle Emissions Cut", f"{co2_saved_transit:.1f} MT CO2e")
    r_col4.metric("Net Carbon Offset", f"{total_co2_offset:.2f} MT CO2e/mo")

    # Waterfall comparison
    scenarios = pd.DataFrame({
        "Category": ["Solar Generation", "Commuter Modal Shift", "Waste Diversion", "Total Offset"],
        "CO2_Reduction_MT": [co2_saved_energy, co2_saved_transit, co2_saved_waste, total_co2_offset]
    })
    fig_impact = px.bar(
        scenarios,
        x="Category",
        y="CO2_Reduction_MT",
        color="Category",
        text_auto=".2f",
        title="Estimated Monthly Carbon Abatement by Initiative (MT CO2e)"
    )
    st.plotly_chart(fig_impact, use_container_width=True)
